[package]
name = "compress-jpeg"
version = "1.0.4"
edition = "2024"
description = "A simple JPEG compression library for WebAssembly"
license = "MIT"
keywords = ["jpeg", "compression", "webassembly", "rust-wasm"]

[dependencies]
js-sys = "0.3.77"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]